apiVersion: appstudio.redhat.com/v1alpha1
kind: IIBAddBundleToIndexImageRequest
metadata:
  labels:
    app.kubernetes.io/name: iibaddbundletoindeximagerequest
    app.kubernetes.io/instance: iibaddbundletoindeximagerequest-sample
    app.kubernetes.io/part-of: internal-services
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: internal-services
  name: iibaddbundletoindeximagerequest-sample
spec:
  # TODO(user): Add fields here
