apiVersion: appstudio.redhat.com/v1alpha1
kind: InternalRequest
metadata:
  labels:
    app.kubernetes.io/name: internalrequest
    app.kubernetes.io/instance: internalrequest-sample
    app.kubernetes.io/part-of: internal-services
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: internal-services
  name: internalrequest-sample
spec:
  # TODO(user): Add fields here
